name: izo_captain
description: "izo captain for pos izo"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+15

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
#  file_picker: ^5.2.0
  path: ^1.8.2
  flutter_svg: ^2.0.9
  fl_chart: ^0.70.2
  data_table_2: ^2.0.3
  liquid_pull_to_refresh: ^3.0.1
  dio:
  get:
  intl: ^0.20.2
  video_player: ^2.9.3
  internet_connection_checker: 1.0.0+1
  lottie: ^3.3.1
  mobile_scanner: 4.0.1
  shared_preferences:
  flutter_spinkit: ^5.2.0
#  flutter_animated_dialog: ^2.0.1
  device_info_plus:
  window_manager:
  http:
  flutter_gutter: ^2.2.0
  font_awesome_flutter:
  animated_snack_bar:
  flutter_cupertino_datetime_picker:
  dropdown_button2: ^2.1.3
  flutter_barcode_listener: ^0.1.3
  flutter_colorpicker:
  pin_keyboard: ^1.1.2
  qr_flutter: ^4.1.0
  settings_ui: ^2.0.2
  barcode_scan2: ^4.3.3
  change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.4.5
  mocktail: ^1.0.4


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/IZOLogo.jpg
    - assets/video/
    - lottie/no_internet.json
    - lottie/


  # example:
  fonts:
    - family: bah
      fonts:
        - asset: assets/fonts/bah.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


