import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Welcome': 'Welcome',
          'To The IZO Captain': 'To The IZO Captain',
          'kindly open the desktop application (IZO) and scan the QR code located in the settings menu under the active mobile app': 'kindly open the desktop application (IZO) and scan the QR code located in the settings menu under the active mobile app',
          'Sorry , Can Not Find The Camera .. !!': 'Sorry , Can Not Find The Camera .. !!',
          'Scan QR': 'Scan QR',
          'Manually': 'Manually',
          'Log In AS Guest': 'Log In AS Guest',
          'Write IP Address Here And Click Connect': 'Write IP Address Here And Click Connect',
          'Can not be Empty !!': 'Can not be Empty !!',
          'Connect': 'Connect',
          'IP Address': 'IP Address',
          'Are You Sure To Rescan QR Code ?': 'Are You Sure To Rescan QR Code ?',
          'You Will Not Be Able To Return To This Page': 'You Will Not Be Able To Return To This Page',
          'No': 'No',
          'Yes': 'Yes',
          'Rescan QR Code': 'Rescan QR Code',
          'LOGIN': 'LOGIN',
          'There may be no internet connection or server error !!': 'There may be no internet connection or server error !!',
          'Select User': 'Select User',
          'Can Not Be Empty !!': 'Can Not Be Empty !!',
          'Please , Select User !!': 'Please , Select User !!',
          'Please , Enter Password !!': 'Please , Enter Password !!',
          'This account is being used on another device. Please log out from other devices !!': 'This account is being used on another device. Please log out from other devices !!',
          'Success Login !!': 'Success Login !!',
          'invalid Password !!': 'invalid Password !!',
          'Are You Sure To Exit ?': 'Are You Sure To Exit ?',
          'Network Error': 'Network Error',
          'Internet Not Found !!': 'Internet Not Found !!',
          'Retry': 'Retry',
          'TakeAway': 'TakeAway',
          'Delivery': 'Delivery',
          "Dine In": "Dine In",
          "TAKEAWAY": "TAKEAWAY",
          "SORRY , NO SERVER CONNECTION !!": "SORRY , NO SERVER CONNECTION !!",
          "SORRY , CAN NOT DELETE !!": "SORRY , CAN NOT DELETE !!",
          "To the kitchen": "To the kitchen",
          "Bill Requested": "Bill Requested",
          "Loading .. ": "Loading .. ",
          "The Table is Busy": "The Table is Busy",
          "Password": "Password",
          "DELIVERY": "DELIVERY",
          "HALL": "HALL",
          "Cancellation Of Reservation": "Cancellation Of Reservation",
          "Are you sure to cancel your reservation?": "Are you sure to cancel your reservation?",
          "Booking Tables": "Booking Tables",
          "Name": "Name",
          "Enter Name": "Enter Name",
          "Mobile Number": "Mobile Number",
          "Guests Number": "Guests Number",
          "Enter Guests Number": "Enter Guests Number",
          "Booking Date": "Booking Date",
          "Select Date Please !": "Select Date Please !",
          "Booking Success !!": "Booking Success !!",
          "Guest Name :": "Guest Name :",
          "Guest Mobil :": "Guest Mobil :",
          "Booking Date :": "Booking Date :",
          "Close": "Close",
          "NO TABLES FOUND OR NO PERMISSION !!": "NO TABLES FOUND OR NO PERMISSION !!",
          "Setting": "Setting",
          "App Setting": "App Setting",
          "Allow To Add Delivery Orders": "Allow To Add Delivery Orders",
          "Add Items Cumulatively To Invoice": "Add Items Cumulatively To Invoice",
          "Theme": "Theme",
          "Enable color item": "Enable color item",
          "POS": "POS",
          "Page Setting": "Page Setting",
          "Orders": "Orders",
          "Customers": "Customers",
          "Price": "Price",
          "Whole Price": "Whole Price",
          "Min price": "Min price",
          "Max Price": "Max Price",
          "Cost Price": "Cost Price",
          "Add Guest": "Add Guest",
          "Guest": "Guest",
          "Enter name": "Enter name",
          "The name is already in use !!": "The name is already in use !!",
          "Cancel": "Cancel",
          "Add": "Add",
          "Address :": "Address :",
          "Note :": "Note :",
          "Qty": "Qty",
          "Units": "Units",
          "Total": "Total",
          "No Order": "No Order",
          "Price/": "Price/",
          "AED": "AED",
          "Whole/": "Whole/",
          "Min/": "Min/",
          "Max/": "Max/",
          "Cost/": "Cost/",
          "There Is No Quantity !!": "There Is No Quantity !!",
          "Send": "Send",
          "Bill Request": "Bill Request",
          "Void": "Void",
          "Search...": "Search...",
          "Add Items Success !!": "Add Items Success !!",
          "View Details": "View Details",
          "Add Customer": "Add Customer",
          "Business name": "Business name",
          "Please enter Mobile number": "Please enter Mobile number",
          "Address": "Address",
          "Enter Address": "Enter Address",
          "Some Thing Wrong !!": "Some Thing Wrong !!",
          "Add Success !!": "Add Success !!",
          "Settings": "Settings",
          "Guests": "Guests",
          "Change Table": "Change Table",
          "All": "All",
          "Single": "Single",
          'Select Order please !!': 'Select Order please !!',
          'Please , Add Some Products !!': 'Please , Add Some Products !!',
          'Select Sum Items And Press Send After That You Can Request The Bill !!': 'Select Sum Items And Press Send After That You Can Request The Bill !!',
          'Press Send Please !!': 'Press Send Please !!',
          'Bill Requested !!': 'Bill Requested !!',
          'Some Thing Wrong !! ': 'Some Thing Wrong !! ',
          'The Quantity is Zero !!': 'The Quantity is Zero !!',
          'BY MISTAKE': 'BY MISTAKE',
          'CHANGE': 'CHANGE',
          'COLD': 'COLD',
          'DELAY': 'DELAY',
          'NOT LIKE': 'NOT LIKE',
          "Can't Be Empty !!": "Can't Be Empty !!",
          "QTY": "QTY",
          "It cannot be increased more !!": "It cannot be increased more !!",
          "It cannot be Decreased more !!": "It cannot be Decreased more !!",
          "Can\'t be Void !! QTY most be bigger than zero !": "It cannot be Decreased more !!",
          "Note Order": "Note Order",
          "Add Note": "Add Note",
          "Update Note": "Update Note",
          "Chose Address and Mobil Number": "Chose Address and Mobil Number",
          "There is no address to add": "There is no address to add",
          "New Address": "New Address",
          "Add New Address !!": "Add New Address !!",
          "New Mobile Number": "New Mobile Number",
          "Add New Mobile Number !!": "Add New Mobile Number !!",
          "Order": "Order",
          "Product": "Product",
          "Sub": "Sub",
          "Main": "Main",
          "Width": "Width",
          "Items In line": "Items In line",
          "Sub Category": "Sub Category",
          "Main Category": "Main Category",
          "Back To Default": "Back To Default",
          "Save": "Save",
          "Add Note ": "Add Note ",
          "Remove": "Remove",
          "Are You Sure To Logout ?": "Are You Sure To Logout ?",
          "Logout Done !!": "Logout Done !!",
          "Logout": "Logout",
          "Enter Pin": "Enter Pin",

          "ERROR": "ERROR",
          "ae": "Arabic",
          "en": "English",
          "us": "English",

        },
        'ar_AR': {
          'Welcome': 'مرحباً',
          'To The IZO Captain': 'الى كابتن IZO',
          'kindly open the desktop application (IZO) and scan the QR code located in the settings menu under the active mobile app': 'يرجى فتح تطبيق سطح المكتب (IZO) ومسح رمز الاستجابة السريعة الموجود في قائمة الإعدادات ضمن تطبيق الهاتف المحمول النشط',
          'Sorry , Can Not Find The Camera .. !!': 'عذرا، لا يمكن العثور على الكاميرا .. !!',
          'Scan QR': 'مسح QR',
          'Manually': 'يدويا',
          'Log In AS Guest': 'تسجيل الدخول كضيف',
          'Write IP Address Here And Click Connect': 'اكتب عنوان IP هنا وانقر على الاتصال',
          'Can not be Empty !!': 'لا يمكن أن يكون فارغا !!',
          'Connect': 'اتصال',
          'IP Address': 'عنوان IP',
          'Are You Sure To Rescan QR Code ?': 'هل أنت متأكد من إعادة مسح رمز الاستجابة السريعة؟',
          'You Will Not Be Able To Return To This Page': 'لن تتمكن من العودة إلى هذه الصفحة',
          'No': 'لا',
          'Yes': 'نعم',
          'Rescan QR Code': 'إعادة مسح رمز الاستجابة السريعة',
          'LOGIN': 'تسجيل الدخول',
          'There may be no internet connection or server error !!': 'قد لا يكون هناك اتصال بالإنترنت أو خطأ في الخادم !!',
          'Select User': 'حدد المستخدم',
          'Can Not Be Empty !!': 'لا يمكن أن يكون فارغا !!',
          'Please , Select User !!': 'من فضلك حدد المستخدم !!',
          'Please , Enter Password !!': 'من فضلك أدخل كلمة المرور!!',
          'This account is being used on another device. Please log out from other devices !!': 'يتم استخدام هذا الحساب على جهاز آخر. يرجى تسجيل الخروج من الأجهزة الأخرى !!',
          'Success Login !!': 'تسجيل دخول ناجح !!',
          'invalid Password !!': 'كلمة المرور غير صالحة!!',
          'Are You Sure To Exit ?': 'هل أنت متأكد من الخروج؟',
          "Network Error": "مشكلة بالشبكه",
          "Internet Not Found !!": "لا يوجد أنترنت",
          "Retry": "اعادة المحاولة",
          'TakeAway': "سفري",
          'Takeaway': "سفري",
          'Tables': "الطاولات",
          'Delivery': "توصيل",
          "Dine In": "طاولات",
          "TAKEAWAY": "سفري",
          "SORRY , NO SERVER CONNECTION !!": "عذرا، لا يوجد اتصال بالخادم !!",
          "SORRY , CAN NOT DELETE !!": "عذرا، لا يمكن الحذف !!",
          "To the kitchen": "إلى المطبخ",
          "Bill Requested": "تم طلب الفاتورة",
          "Loading .. ": "إنتظر ...",
          "The Table is Busy": "الطاولة مشغولة",
          "Password": "كلمة السر",
          "DELIVERY": "توصيل",
          "HALL": "قاعة",
          "Cancellation Of Reservation": "إلغاء الحجز",
          "Are you sure to cancel your reservation?": "هل أنت متأكد من إلغاء حجزك؟",
          "Booking Tables": "جداول الحجز",
          "Name": "الاسم",
          "Enter Name": "أدخل الاسم",
          "Mobile Number": "أدخل الجوال",
          "Guests Number": "عدد الضيوف",
          "Enter Guests Number": "أدخل رقم الضيوف",
          "Booking Date": "تاريخ الحجز",
          "Select Date Please !": "اختر التاريخ من فضلك!",
          "Booking Success !!": "اختر التاريخ من فضلك!",
          "Guest Name :": "اسم الضيف :",
          "Guest Mobil :": "رقم الموبايل",
          "Booking Date :": "تاريخ الحجز :",
          "Close": "يغلق",
          "NO TABLES FOUND OR NO PERMISSION !!": "لم يتم العثور على طاولات أو لا يوجد إذن !!",
          "Setting": "أعدادات",
          "App Setting": "اعدادات التطبيق",
          "Allow To Add Delivery Orders": "السماح بإضافة طلبات التوصيل",
          "Add Items Cumulatively To Invoice": "إضافة العناصر بشكل تراكمي إلى الفاتورة",
          "Theme": "ثيمات",
          "Enable color item": "تفعيل اللون للعناصر",
          "POS": "نقطة البيع",
          "Page Setting": "اعدادات نقطة البيع",
          "Orders": "طلبات",
          "Customers": "عملاء",
          "Price": "سعر",
          "Whole Price": "السعر الكامل",
          "Min price": "الحد الأدنى للسعر",
          "Max Price": "الحد الأعلى",
          "Cost Price": "سعر التكلفه",
          "Add Guest": "إضافة ضيف",
          "Guest": "ضيف",
          "Enter name": "أدخل الاسم",
          "The name is already in use !!": "الاسم تم استخدامه بالفعل !!",
          "Cancel": "الغاء",
          "Add": "إظافه",
          "Address :": "العنوان :",
          "Note :": "الملاحظه : ",
          "Qty": "الكميه",
          "Units": "الوحدة",
          "Total": "المجموع",
          "No Order": "ليس هنالك طلبات",
          "Price/": "السعر/",
          "AED": "درهم",
          "Whole/": "الكامل/",
          "Min/": "اقل/",
          "Max/": "اكثر/",
          "Cost/": "تكلفة/",
          "There Is No Quantity !!": "لا يوجد كمية !!",
          "Send": "ارسال",
          "Bill Request": "طلب الفاتورة",
          "Void": "مرتجع",
          "Search...": "يبحث...",
          "Add Items Success !!": "تمت إضافة العناصر بنجاح !!",
          "View Details": "عرض التفاصيل",
          "Add Customer": "إضافة العميل",
          "Business name": "اسم الشركه",
          "Please enter Mobile number": "الرجاء إدخال رقم الجوال",
          "Address": "العنوان",
          "Enter Address": "ادخل العنوان",
          "Some Thing Wrong !!": "هناك خطب ما !!",
          "Add Success !!": "تم الأضافة !!",
          "Settings": "أعدادات",
          "Guests": "الضيوف",
          "Change Table": "تغيير الطاوله",
          "All": "الكل",
          "Single": "فردي",
          'Select Order please !!': 'اختر الطلب من فضلك!!',
          'Please , Add Some Products !!': 'من فضلك أضف بعض المنتجات !!',
          'Select Sum Items And Press Send After That You Can Request The Bill !!': 'قم باختيار مجموع العناصر ثم اضغط على إرسال وبعد ذلك يمكنك طلب الفاتورة !!',
          'Press Send Please !!': 'اضغط على إرسال من فضلك !!',
          'Bill Requested !!': 'مطلوب فاتورة !!',
          'Some Thing Wrong !! ': 'هل هناك خطب ما !!',
          'The Quantity is Zero !!': 'الكمية هي صفر !!',
          'BY MISTAKE': 'عن طريق الخطأ',
          'CHANGE': 'يتغير',
          'COLD': 'بارد',
          'DELAY': 'تأخير',
          'NOT LIKE': 'لم يحبه',
          "Can't Be Empty !!": "لا يمكن أن يكون فارغا !!",
          "QTY": "الكميه",
          "It cannot be increased more !!": "لا يمكن زيادتها أكثر !!",
          "It cannot be Decreased more !!": "لا يمكن أن ينقص أكثر من ذلك !!",
          "Can\'t be Void !! QTY most be bigger than zero !": "لا يمكن أن ينقص أكثر من ذلك !!",
          "Note Order": "ملاحظة الطلب",
          "Add Note": "أضف ملاحظة",
          "Update Note": "تحديث الملاحظة",
          "Chose Address and Mobil Number": "اختر العنوان ورقم الجوال",
          "There is no address to add": "لا يوجد عنوان لإضافته",
          "New Address": "العنوان الجديد",
          "Add New Address !!": "أضف عنوان جديد !!",
          "New Mobile Number": "رقم الجوال الجديد",
          "Add New Mobile Number !!": "أضف رقم جوال جديد !!",
          "Order": "طلب",
          "Product": "منتج",
          "Sub": "الفرعية",
          "Main": "رئيسي",
          "Width": "عرض",
          "Items In line": "العناصر في السطر",
          "Sub Category": "الفئة الفرعية",
          "Main Category": "الفئة الرئيسية",
          "Back To Default": "الأعدادات الافتراضيه",
          "Save": "حفظ",
          "Add Note ": "أضف ملاحظة",
          "Remove": "حذف",
          "Are You Sure To Logout ?": "هل أنت متأكد من تسجيل الخروج؟",
          "Logout Done !!": "تم تسجيل الخروج !!",
          "Logout": "تسجيل الخروج",
          "Enter Pin": "أدخل رقم التعريف الشخصي",
          "ERROR": "خطأ",
          "ae": "العربيه",
          "en": "الإنجليزيه",
          "us": "الإنجليزيه",
        },
      };
}
